### ISSUE TITLE
[BUG] ecs-svc discovery includes all services in a cluster, and metric labels come from an arbitrary service

### ISSUE THREAD

**Issue by nhinds** [nerdswords/yet-another-cloudwatch-exporter#627] opened 2022-07-28 05:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, if any service in an ECS cluster matches the `searchTags` in an `ecs-svc` discovery job, metrics for *all* services in that ECS cluster will be scraped.

When `exportedTagsOnMetrics` is specified, the tags from the matched service will be associated with metrics from all services. If multiple services in an ECS cluster match the `searchTags`, tags from an arbitrary service will be applied to all metrics.

### Expected Behavior

If only one service in an ECS cluster match the `searchTags` (and the cluster itself does not match), only that single service should have its metrics scraped.

If multiple services match `searchTags`, the tags from each ECS service should be applied to its own metric

### Steps To Reproduce

1. Create an ECS cluster with two services, tagged with `Service=<something>` and `Role=<something different per service>`
2. Configure `yace` to scrape ECS services with `Service=<something>` and `Role=<one value>`, and to copy the `Service` and `Role` tags to metrics:
```
discovery:
  exportedTagsOnMetrics:
    ecs-svc:
    - Role
    - Service
  jobs:
  - type: ecs-svc
    regions:
    - ap-southeast-2
    searchTags:
    - key: Service
      value: <something>
    - key: Role
      value: <one of the role values>
    length: 1200
    period: 60
    metrics:
    - name: CPUUtilization
      statistics: [Maximum]
      nilToZero: true

```
3. Check the metrics. Only the matching ECS service is present in `aws_ecs_svc_info`, but `aws_ecs_svc_cpuutilization_maximum` includes the other ECS service with the wrong tags (though the `dimension_ServiceName` label is correct):
```
# HELP aws_ecs_svc_cpuutilization_maximum Help is not implemented yet.
# TYPE aws_ecs_svc_cpuutilization_maximum gauge
aws_ecs_svc_cpuutilization_maximum{account_id="1234567890",dimension_ClusterName="my-cluster-name",dimension_ServiceName="matching-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/matching-service",region="ap-southeast-2",tag_Role="<one of the role values>",tag_Service="<something>"} 5.492108138082059
aws_ecs_svc_cpuutilization_maximum{account_id="1234567890",dimension_ClusterName="my-cluster-name",dimension_ServiceName="other-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/matching-service",region="ap-southeast-2",tag_Role="<one of the role values>",tag_Service="<something>"} 13.422734092626918
# HELP aws_ecs_svc_info Help is not implemented yet.
# TYPE aws_ecs_svc_info gauge
aws_ecs_svc_info{name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/matching-service",tag_Role="<one of the role values>",tag_Service="<something>"} 0
```
4. Remove `Role` from `searchTags`
```
```
discovery:
  exportedTagsOnMetrics:
    ecs-svc:
    - Role
    - Service
  jobs:
  - type: ecs-svc
    regions:
    - ap-southeast-2
    searchTags:
    - key: Service
      value: <something>
    length: 1200
    period: 60
    metrics:
    - name: CPUUtilization
      statistics: [Maximum]
      nilToZero: true

```
```
5. Check the metrics again. Both ECS services will be present in `aws_ecs_svc_info` with the correct tags (and in my case, the ECS cluster itself also matches), but the `aws_ecs_svc_cpuutilization_maximum` metrics all have the tags of an arbitrary matching service:
```
# HELP aws_ecs_svc_cpuutilization_maximum Help is not implemented yet.
# TYPE aws_ecs_svc_cpuutilization_maximum gauge
aws_ecs_svc_cpuutilization_maximum{account_id="1234567890",dimension_ClusterName="my-cluster-name",dimension_ServiceName="matching-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/other-service",region="ap-southeast-2",tag_Role="<other role value>",tag_Service="<something>"} 5.550455194040153
aws_ecs_svc_cpuutilization_maximum{account_id="1234567890",dimension_ClusterName="my-cluster-name",dimension_ServiceName="other-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/other-service",region="ap-southeast-2",tag_Role="<other role value>",tag_Service="<something>"} 14.431799231013773
# HELP aws_ecs_svc_info Help is not implemented yet.
# TYPE aws_ecs_svc_info gauge
aws_ecs_svc_info{name="arn:aws:ecs:ap-southeast-2:1234567890:cluster/my-cluster-name",tag_Role="<cluster role>",tag_Service="<something>"} 0
aws_ecs_svc_info{name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/matching-service",tag_Role="<one of the role values>",tag_Service="<something>"} 0
aws_ecs_svc_info{name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/other-service",tag_Role="<other role value>",tag_Service="<something>"} 0
```

### Anything else?

I tried updating the regex in `pkg/services.go` to also extract the `ServiceName` dimension (`service/(?P<ClusterName>[^/]+)/(?P<ServiceName>[^/]+)`). This seems to fix the first problem, as only metrics from matching services get scraped in that case, but it does not fix the second problem - if 2 or more services match `searchTags` then their metrics still all have the tag labels from a single service instead of their own tags.

In my account at least, it seems like the `AWS/ECS` metric dimensions are returned in the order `[ServiceName, ClusterName]`. The logic in `getFilteredMetricDatas` uses the last resource that matches the last dimension, even if earlier dimensions do not match the resource. I'm not sure what the impact would be if `getFilteredMetricDatas` was changed to only select resources that match all dimensions, it seems quite complex at the moment.

**Comment by thepalbi** [comment] 2023-03-30 17:47
Tried to replicate the issue described above to see if the new dimensions to resource matching algorithm introduced in https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/821 solves it.

The resources created are:
1. ECS cluster, named yace-cluster
1. One ECS service, tagged
  1. `Service=nginx`
  1. `Instance=first`
1. Other ECS service, tagged
  1. `Service=nginx`
  1. `Instance=second`
  
I tried replicating the three possible scenarios (both services matched, just the first one and just the second one):
```yaml
apiVersion: v1alpha1
sts-region: us-east-2
discovery:
  exportedTagsOnMetrics:
    AWS/ECS:
      - Service
      - Instance
  jobs:

    - type: AWS/ECS
      regions: [us-east-2]
      searchTags:
        - key: Service
          value: nginx
        - key: Instance
          value: first
      customTags:
        - key: experiment
          value: just_service_first
      period: 300
      length: 300
      metrics:
        - name: CPUUtilization
          statistics:
            - Maximum

    - type: AWS/ECS
      regions: [us-east-2]
      searchTags:
        - key: Service
          value: nginx
        - key: Instance
          value: second
      customTags:
        - key: experiment
          value: just_service_second
      period: 300
      length: 300
      metrics:
        - name: CPUUtilization
          statistics:
            - Maximum

    - type: AWS/ECS
      regions: [us-east-2]
      searchTags:
        - key: Service
          value: nginx
      customTags:
        - key: experiment
          value: both
      period: 300
      length: 300
      metrics:
        - name: CPUUtilization
          statistics:
            - Maximum
```

Producing the following results:

<img width="2208" alt="image" src="https://user-images.githubusercontent.com/2617411/228921045-f0224c2c-5898-40a5-957d-f0ad6a2b3d13.png">

You can notice there's one panel per `experiment` tag, in which each discovery job replicates one filtering and matching scenario. My guess is that `searchTags` is actually working (since it only works at the resource level in YACE), and the root cause was actually the matching algo, which is now fixed.

**Comment by nhinds** [comment] 2023-03-31 03:50
I re-tested with versions `v0.48.0-alpha` and `v0.49.2`. Both versions still return `aws_ecs_svc_cpuutilization_maximum` metrics with `name` and `tag_*` labels for a random/arbitrary ECS service, not the one associated with `dimension_ServiceName`.

Re-test results from step 3 (filtering by `Service` and `Role` tags) from `v0.49.2`, showing both services incorrectly returned, with the labels from the matching service applied to both:
```
# HELP aws_ecs_svc_cpuutilization_maximum Help is not implemented yet.
# TYPE aws_ecs_svc_cpuutilization_maximum gauge
aws_ecs_svc_cpuutilization_maximum{account_id="1234567890",dimension_ClusterName="my-cluster-name",dimension_ServiceName="matching-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/matching-service",region="ap-southeast-2",tag_Role="<one of the role values>",tag_Service="<something>"} 9.265194143913686
aws_ecs_svc_cpuutilization_maximum{account_id="1234567890",dimension_ClusterName="my-cluster-name",dimension_ServiceName="other-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/matching-service",region="ap-southeast-2",tag_Role="<one of the role values>",tag_Service="<something>"} 14.158515577008457
# HELP aws_ecs_svc_info Help is not implemented yet.
# TYPE aws_ecs_svc_info gauge
aws_ecs_svc_info{name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/matching-service",tag_Role="<one of the role values>",tag_Service="<something>"} 0
```

Re-test results from step 5 (filtering only by `Service`) from `v0.49.2`, showing both services returned, but with the labels from one of the services arbitrarily applied to both:
```
# HELP aws_ecs_svc_cpuutilization_maximum Help is not implemented yet.
# TYPE aws_ecs_svc_cpuutilization_maximum gauge
aws_ecs_svc_cpuutilization_maximum{account_id="1234567890",dimension_ClusterName="my-cluster-name",dimension_ServiceName="matching-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/other-service",region="ap-southeast-2",tag_Role="<other role value>",tag_Service="<something>"} 14.758713329816237
aws_ecs_svc_cpuutilization_maximum{account_id="1234567890",dimension_ClusterName="my-cluster-name",dimension_ServiceName="other-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/other-service",region="ap-southeast-2",tag_Role="<other role value>",tag_Service="<something>"} 13.976033274689689
# HELP aws_ecs_svc_info Help is not implemented yet.
# TYPE aws_ecs_svc_info gauge
aws_ecs_svc_info{name="arn:aws:ecs:ap-southeast-2:1234567890:cluster/my-cluster-name",tag_Role="<cluster role>",tag_Service="<something>"} 0
aws_ecs_svc_info{name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/matching-service",tag_Role="<one of the role values>",tag_Service="<something>"} 0
aws_ecs_svc_info{name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/other-service",tag_Role="<other role value>",tag_Service="<something>"} 0
```

I also tried running the configuration from your comment with 3 scrape jobs, with my tag keys/values swapped in. I had 6 `aws_ecs_cpuutilization_maximum` metrics returned (2 for each of the 3 scrape jobs), and each scrape job had chosen one of the services and incorrectly applied that service's tags to both services, though `dimension_ServiceName` is correct as always:
```
# HELP aws_ecs_cpuutilization_maximum Help is not implemented yet.
# TYPE aws_ecs_cpuutilization_maximum gauge
aws_ecs_cpuutilization_maximum{account_id="1234567890",custom_tag_experiment="both",dimension_ClusterName="my-cluster-name",dimension_ServiceName="first-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/second-service",region="ap-southeast-2",tag_Role="<second role>",tag_Service="<something>"} 15.175374036561697
aws_ecs_cpuutilization_maximum{account_id="1234567890",custom_tag_experiment="both",dimension_ClusterName="my-cluster-name",dimension_ServiceName="second-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/second-service",region="ap-southeast-2",tag_Role="<second role>",tag_Service="<something>"} 14.424753446818183
aws_ecs_cpuutilization_maximum{account_id="1234567890",custom_tag_experiment="just_service_first",dimension_ClusterName="my-cluster-name",dimension_ServiceName="first-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/first-service",region="ap-southeast-2",tag_Role="<first role>",tag_Service="<something>"} 15.175374036561697
aws_ecs_cpuutilization_maximum{account_id="1234567890",custom_tag_experiment="just_service_first",dimension_ClusterName="my-cluster-name",dimension_ServiceName="second-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/first-service",region="ap-southeast-2",tag_Role="<first role>",tag_Service="<something>"} 14.424753446818183
aws_ecs_cpuutilization_maximum{account_id="1234567890",custom_tag_experiment="just_service_second",dimension_ClusterName="my-cluster-name",dimension_ServiceName="first-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/second-service",region="ap-southeast-2",tag_Role="<second role>",tag_Service="<something>"} 15.175374036561697
aws_ecs_cpuutilization_maximum{account_id="1234567890",custom_tag_experiment="just_service_second",dimension_ClusterName="my-cluster-name",dimension_ServiceName="second-service",name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/second-service",region="ap-southeast-2",tag_Role="<second role>",tag_Service="<something>"} 14.424753446818183
# HELP aws_ecs_info Help is not implemented yet.
# TYPE aws_ecs_info gauge
aws_ecs_info{name="arn:aws:ecs:ap-southeast-2:1234567890:cluster/my-cluster-name",tag_Role="<cluster role>",tag_Service="<something>"} 0
aws_ecs_info{name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/first-service",tag_Role="<first role>",tag_Service="<something>"} 0
aws_ecs_info{name="arn:aws:ecs:ap-southeast-2:1234567890:service/my-cluster-name/second-service",tag_Role="<second role>",tag_Service="<something>"} 0
```


When you were testing your configuration, was your ECS cluster itself also tagged `Service=nginx` (and returned in `aws_ecs_info`)?

I have also tried adding `dimensionNameRequirements: [ClusterName, ServiceName]` to ensure only metrics for ECS services are scraped, not cluster-wide metrics, but this did not impact how labels were applied.

It does not look like this is fixed in `v0.49.2`, at least for me.

I see that #821 is still open, is there a different version or branch with updated logic that I should re-test this on?

**Comment by nhinds** [comment] 2023-03-31 04:21
Ah, I found your branch on #833 and updated my code to pass `yace.EnableFeatureFlag(config.EncodingResourceAssociator)` to enable it. With that change, the labels look better.

Using your config example I still get 6 `aws_ecs_cpuutilization_maximum` metrics, but 2 of them are `name="global"` and their `tag_*` labels are empty (instead of copying tags/labels from a random service). I'm already using `dimensionNameRequirements` to stop yace from returning hundreds of these `name="global"` metrics for other services, and adding `dimensionNameRequirements: [ClusterName, ServiceName]` makes the metrics behave correctly - `experiment="both"` has 2 series with the correct tag labels, and the 2 `experiment="just_service_*"` jobs each have a single series with the correct tag labels.

Using my own configuration with a single job, the tag labels are also correctly applied. It looks like when #833 is merged, this issue will also be fixed for people who opt into the `EncodingResourceAssociator` feature flag. Without that flag the labels are still incorrect.

One difference is that if your ECS cluster matches the search tags but your ECS services do not, previously metrics for all services in the cluster would be returned but with your branch untagged services are not returned at all. This seems sensible behaviour, but it _is_ one difference that people might not be expecting.

I have not checked the impact of #833 on other resource types in my configuration, but I can do so next week.

**Comment by thepalbi** [comment] 2023-03-31 04:23
@nhinds can you re-try the scenarios with [this branch](https://github.com/thepalbi/yet-another-cloudwatch-exporter/tree/pablo/fix-association-issue) (it's in my fork), and the following flag 

`-enable-feature=encoding-resource-associator`

when running YACE?

Also, to see if we tested with a similar setup, the ECS setup I used is this one:
```terraform
# cluster
resource "aws_ecs_cluster" "cluster" {
  name = "yace-cluster"
  tags = {
    Name = "yace-cluster"
  }
}

resource "aws_ecs_task_definition" "task" {
  family                   = "service"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE", "EC2"]
  cpu                      = 256
  memory                   = 512
  container_definitions    = <<DEFINITION
  [
    {
      "name"      : "nginx",
      "image"     : "nginx:1.23.1",
      "cpu"       : 256,
      "memory"    : 512,
      "essential" : true,
      "portMappings" : [
        {
          "containerPort" : 80,
          "hostPort"      : 80
        }
      ]
    }
  ]
  DEFINITION
}

resource "aws_ecs_service" "service" {
  name             = "service"
  cluster          = aws_ecs_cluster.cluster.id
  task_definition  = aws_ecs_task_definition.task.id
  desired_count    = 1
  launch_type      = "FARGATE"
  platform_version = "LATEST"

  network_configuration {
    assign_public_ip = true
    security_groups  = [aws_security_group.sg.id]
    subnets          = [aws_subnet.subnet.id]
  }
  lifecycle {
    ignore_changes = [task_definition]
  }

  tags = {
    Service = "nginx"
    Instance = "first"
  }
}

resource "aws_ecs_service" "service2" {
  name             = "service2"
  cluster          = aws_ecs_cluster.cluster.id
  task_definition  = aws_ecs_task_definition.task.id
  desired_count    = 1
  launch_type      = "FARGATE"
  platform_version = "LATEST"

  network_configuration {
    assign_public_ip = true
    security_groups  = [aws_security_group.sg.id]
    subnets          = [aws_subnet.subnet.id]
  }
  lifecycle {
    ignore_changes = [task_definition]
  }

  tags = {
    Service = "nginx"
    Instance = "second"
  }
}
```

**Comment by thepalbi** [comment] 2023-03-31 04:32
@nhinds 
> Without that flag the labels are still incorrect.

Yhea after discussing with @cristiangreco we agreed on adding this change under a feature flag, since it might the labels in metrics (for the better, but different still).

> One difference is that if your ECS cluster matches the search tags but your ECS services do not, previously metrics for all services in the cluster would be returned but with your branch untagged services are not returned at all. This seems sensible behaviour, but it is one difference that people might not be expecting.

By this you mean that if I do a job like:
```yaml
 - type: AWS/ECS
      regions: [us-east-2]
      searchTags:
        - key: Service
          value: nginx
        - key: Instance
          value: asdiaojdwoijdoa
      period: 300
      length: 300
      metrics:
        - name: CPUUtilization
          statistics:
            - Maximum
```

no metric would be returned, since no resource matches that those `searchTags`?

**Comment by nhinds** [comment] 2023-03-31 06:10
Rather than no resources matching the tags, I'm talking about the case where the ECS cluster's tags match, but the ECS services do not. In your Terraform, since you applied the tag `Name = "yace-cluster"` to your cluster but not to your services, the yace config to match the ECS cluster and not the ECS services would be something like:
```
searchTags:
- key: Name
  value: yace-cluster
```

In `v0.49.2` and with the code currently on the `master` branch, metrics are returned for all services in the cluster, and in your branch it returns no metrics in this scenario even with the feature flag turned off. It might be related to the `DimensionRegexps` changes? It's not too important though, I think that for metrics that apply to ECS services, requiring the ECS services themselves to be tagged makes sense anyway.

**Comment by nhinds** [comment] 2023-04-05 05:57
I tested that branch with my full YACE config to see what impact it had on other resources.

When using the default associator, the metrics look the same as the current version I'm using.

When using the 'encoding resource associator', all of my ALB and NLB metrics lose their tags. I've left a comment over on #833.

**Comment by cristiangreco** [comment] 2023-04-16 20:07
I've taken heavy inspiration from @thepalbi's PR and rewritten the matching algorithm in https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/898

@nhinds would you please be able to test the branch `cristian/max-dim-assoc`? You'll need to enable the new algorithm via the feature flag `-enable-feature=max-dimensions-associator`.

**Comment by nhinds** [comment] 2023-04-17 00:49
The branch `cristian/max-dim-assoc` appears to solve the issue as originally described. When selecting a single ECS service by tags, only that service gets a `aws_ecs_svc_cpuutilization_maximum` metric and the labels are correct. When selecting multiple ECS services by tags, multiple `aws_ecs_svc_cpuutilization_maximum` metrics are returned and their labels match their service.

Enabling the flag causes many "skipping resource unmatched by associator" messages to be logged, and that message appears to be incorrect. It is [logged for every metric that exists in cloudwatch logs that does not have a matching resource](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/cristian/max-dim-assoc/pkg/job/discovery.go#L267) (i.e. it is logged when a _metric_ is skipped), but it says it is skipping a _resource_. In AWS accounts where I might have hundreds of resources and only want to monitor a small handful, this is going to cause a huge amount of log spam for every set of metric dimensions I am not interested in.

e.g. when selecting a single metric for a single ECS service in a single region with 7 ECS services in total, there are 7 "skipping resource unmatched by associator" messages (6 with the dimensions of the other non-matching ECS services, plus one with the dimensions of the ECS cluster itself)

e.g. when running with my normal configuration, each scrape logs "skipping resource unmatched by associator" 695 times.

Could that log message be downgraded to debug, since it's somewhat normal for metrics to exist in cloudwatch that don't correspond to an AWS resource I'm targeting with tags?

All of my DMS metrics also disappear when using the `MaxDimensionsAssociator` feature flag, though they are still present on your branch when not using that flag. This seems to be because I'm scraping metrics with dimensions `[ReplicationInstanceIdentifier, ReplicationTaskIdentifier]`, but relying on the tagging of the replication instance (which is tagged) rather than the replication task (which is apparently not tagged). Previously it was associating those metrics with the replication instance, but now they are skipped because a regex with more specific dimensions exists (`task:(?P<ReplicationTaskIdentifier>[^/]+)/(?P<ReplicationInstanceIdentifier>[^/]+)`) and no resources match that regex. This is probably fine, since it makes some sense that retrieving metrics for DMS tasks requires those tasks to be tagged rather than just the instance, but it's worth knowing that it's a change

**Comment by nhinds** [comment] 2023-04-17 22:03
Sorry, I'm not comfortable granting that kind of read access into my AWS account. Thank you for offering to re-test though.

**Comment by cristiangreco** [comment] 2023-05-05 13:14
Marking this as fixed in v0.51.0 with the use of the `-enable-feature=max-dimensions-associator` flag.

**Closed by cristiangreco** 2023-05-05 13:14 UTC
Labels: bug

**Comment by jdix531** [comment] 2023-08-09 14:20
@cristiangreco Is there plans to make this the default behavior? Requiring an optional feature to fix a bug is a great start but was thinking it would make more sense as the default if it has been working.

**Comment by thepalbi** [comment] 2023-08-15 21:06
I think we should, we've been using it internally for a while now, and got no complaints. @cristiangreco is out for vacation until next week, but +1. Also poking @kgeckhart for opinions

**Comment by matiasba** [comment] 2024-07-05 19:55
This really seems like it should be the default behavior. I had to go look through all the issues to find why I was seeing a bunch of metrics that should not be there. @cristiangreco
