### ISSUE TITLE
[BUG] AmazonMQ No metrics data found

### ISSUE THREAD

**Issue by vihongu** [nerdswords/yet-another-cloudwatch-exporter#912] opened 2023-04-26 15:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

since v0.39.0-alpha

### Config file

apiVersion: v1alpha1
sts-region: eu-central-1
discovery:
  jobs:
    - type: mq
      regions:
        - eu-central-1
      period: 300
      length: 300
      metrics:
        - name: CpuUtilization
          statistics:
            - Maximum

### Current Behavior

Works with version v0.38.0-alpha

After update to newer yace version:
No Metric Data for AmazonMQ
Debug Logs:
{"account":"1234","arn":"","job_type":"mq","level":"debug","msg":"No metrics data found","region":"eu-central-1","time":"2023-04-26T15:04:46Z"}

### Expected Behavior

Metrics Data found.

### Steps To Reproduce

Tested versions v0.39.0-alpha to v0.50.0

**Comment by cristiangreco** [comment] 2023-04-26 15:51
Hi @vihongu, are your resources correctly tagged? Can you please post the output of `aws cloudwatch list-metrics --namespace mq`? Thanks!

**Comment by ChrisDBaldwin** [comment] 2023-04-26 18:39
We are seeing the same issue with AmazonMQ and discovery configs. Our output for that command is very empty. Note that `mq` is not the typical namespace, and using ```AWS/AmazonMQ``` returns what we'd expect.

```aws cloudwatch list-metrics --namespace mq``` returns:
```
{
    "Metrics": []
}
```

**Comment by cristiangreco** [comment] 2023-04-26 19:51
So probably `mq` is not a correct alias for `AWS/AmazonMQ`, we might need to remove it.

**Comment by ChrisDBaldwin** [comment] 2023-04-26 20:04
From our experience, it appears as though discovery is working, but mapping dimensions from metrics results in "No metrics data found".

**Comment by jesselang** [comment] 2023-04-26 21:34
@cristiangreco, I've added a test for the associator in #914  that I believe represents the behavior that @ChrisDBaldwin and I are seeing. The discovery of ActiveMQ brokers appears to work correctly, but metrics have a dimension with a numbered suffix (i.e. `-1`) whether it is a single-instance broker or active standby broker configuration. In an active/standby configuration, each broker would push a metric (i.e. `sampleBroker-1', `sampleBroker-2`, `sampleBroker-3`). It seems we need a way to tell the associator how to match the dimension. Perhaps a match function could be used that could be defined for each service supported by auto-discovery?

I'll look at adding a test case for the max dimension associator next. We appreciate your insights toward resolving this. Thanks!

**Comment by vihongu** [comment] 2023-04-27 07:41
Hi, thanks for your response!

The output of the command is:
{
    "Metrics": [ ]
}

With aws cloudwatch list-metrics --namespace AWS/AmazonMQ we got the list of our metrics. 

We also tested the config 

jobs:
- type: AWS/AmazonMQ

with the same output. ("msg":"No metrics data found")

**Comment by cristiangreco** [comment] 2023-04-27 07:57
So this is about two different issues I think:
- one is the fact that `type: AWS/AmazonMQ` should be used in place of `type: mq`
- the other problem the peculiar name of broker with a numbered suffix. I think this has been reported in the past, but I kinda remember it only affected active/standby pairs (i.e. single instance brokers don't have the suffix)

I'll try to reproduce that this week.

**Comment by cristiangreco** [comment] 2023-04-28 14:19
I believe this is fixed in https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/917

You'll need to use `-enable-feature=max-dimensions-associator`, because the fix on the old associator algorithm is messy. Would you be able to test it and confirm?

(PS: I decided to special-case the AmazonMQ matching rather than introducing a generic mechanism for matching weird names. If this pattern comes up more often then the code can be reworked)

**Comment by RetroJumper** [comment] 2023-04-28 19:05
Built a image from Branch #917 and used the feature flag, confirmed metrics are being exported properly thanks!

**Comment by cristiangreco** [comment] 2023-05-05 13:12
Closing this ticket now that #917 has been merged.

**Closed by cristiangreco** 2023-05-05 13:12 UTC
Labels: bug
